
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerVDModuleWidgets_h
#define __osm_qSlicerVDModuleWidgets_h

#include <QObject>
#include "qSlicerVDFooBarWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerVDFooBarWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerVDFooBarWidget* new_qSlicerVDFooBarWidget(QWidget*  parent = 0)
    {
    return new qSlicerVDFooBarWidget(parent);
    }
  void delete_qSlicerVDFooBarWidget(qSlicerVDFooBarWidget* obj) { delete obj; }
};

#endif
