# Common settings
set(CTKAPPLAUNCHER_SETTINGS_TEMPLATE "C:/D/S4R/CTKAPPLAUNCHER/bin/CTKAppLauncherSettings.ini.in")
set(CTKAPPLAUNCHER_APPLICATION_EXECUTABLE_NAME "Slicer.exe")
set(CTKAPPLAUNCHER_APPLICATION_NAME "SlicerWithVirtualDissection")
set(CTKAPPLAUNCHER_APPLICATION_REVISION "")
set(CTKAPPLAUNCHER_ORGANIZATION_DOMAIN "")
set(CTKAPPLAUNCHER_ORGANIZATION_NAME "")
set(CTKAPPLAUNCHER_DESTINATION_DIR "C:/dev/SlicerFirstExtension/VirtualDissection-build")
set(CTKAPPLAUNCHER_SPLASHSCREEN_DISABLED "false")
set(CTKAPPLAUNCHER_SPLASHSCREEN_HIDE_DELAY_MS "")
set(CTKAPPLAUNCHER_HELP_SHORT_ARG "")
set(CTKAPPLAUNCHER_HELP_LONG_ARG "")
set(CTKAPPLAUNCHER_NOSPLASH_ARGS "")
set(CTKAPPLAUNCHER_APPLICATION_DEFAULT_ARGUMENTS "--launcher-additional-settings C:/dev/SlicerFirstExtension/VirtualDissection-build/AdditionalLauncherSettings.ini --additional-module-paths C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-scripted-modules C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Debug C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/cli-modules/Debug C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Release C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/cli-modules/Release C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/cli-modules/MinSizeRel C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/cli-modules/RelWithDebInfo")
set(CTKAPPLAUNCHER_SPLASH_IMAGE_NAME "")
set(CTKAPPLAUNCHER_USER_ADDITIONAL_SETTINGS_FILEBASENAME_SET "")
set(CTKAPPLAUNCHER_LAUNCHER_LOAD_ENVIRONMENT_SET "")
set(CTKAPPLAUNCHER_ADDITIONAL_SETTINGS_EXCLUDE_GROUPS_SET "")
# Specific settings
set(CTKAPPLAUNCHER_APPLICATION_SUBDIR "<APPLAUNCHER_DIR>/")
set(CTKAPPLAUNCHER_SPLASH_IMAGE_SUBDIR "")
set(CTKAPPLAUNCHER_ADDITIONAL_SETTINGS_FILEPATH_SET "")
set(CTKAPPLAUNCHER_EXTRA_APPLICATION_TO_LAUNCH "")
set(CTKAPPLAUNCHER_LIBRARY_PATHS "size=0")
set(CTKAPPLAUNCHER_PATHS "size=0")
set(CTKAPPLAUNCHER_ENVVARS "")
set(CTKAPPLAUNCHER_ADDITIONAL_PATH_ENVVARS "")
set(CTKAPPLAUNCHER_ADDITIONAL_PATHS "")
