
set(Slicer_CMAKE_DIR "C:/D/S4/CMake")
set(MIDAS_PACKAGE_URL "http://slicer.kitware.com/midas3")
set(MIDAS_PACKAGE_EMAIL "YOUR-MIDAS-LOGIN-NOTFOUND")
set(MIDAS_PACKAGE_API_KEY "YOUR-MIDAS-APIKEY-NOTFOUND")
set(SLICER_EXTENSION_MANAGER_CLIENT_EXECUTABLE "SLICER_EXTENSION_MANAGER_CLIENT_EXECUTABLE-NOTDEFINED")
set(SLICER_EXTENSION_MANAGER_URL "SLICER_EXTENSION_MANAGER_URL-NOTDEFINED")
set(SLICER_EXTENSION_MANAGER_API_KEY "SLICER_EXTENSION_MANAGER_API_KEY-NOTDEFINED")
set(CTEST_MODEL "Experimental")
set(Slicer_REVISION "30175")
set(EXTENSION_NAME "VirtualDissection")
set(EXTENSION_CATEGORY "Examples")
set(EXTENSION_ICONURL "http://www.example.com/Slicer/Extensions/VirtualDissection.png")
set(EXTENSION_CONTRIBUTORS "Lucas Rodrigues (AnyWare Corp.)")
set(EXTENSION_DEPENDS "NA")
set(EXTENSION_DESCRIPTION "This is an example of a simple extension")
set(EXTENSION_HOMEPAGE "https://www.slicer.org/wiki/Documentation/Nightly/Extensions/VirtualDissection")
set(EXTENSION_SCREENSHOTURLS "http://www.example.com/Slicer/Extensions/VirtualDissection/Screenshots/1.png")
set(EXTENSION_ENABLED "1")
set(EXTENSION_OPERATING_SYSTEM "win")
set(EXTENSION_ARCHITECTURE "amd64")
set(EXTENSION_WC_TYPE "local")
set(EXTENSION_WC_URL "NA")
set(EXTENSION_WC_REVISION "0")
set(EXTENSION_BINARY_DIR "C:/dev/SlicerFirstExtension/VirtualDissection-build/.")