# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.19)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget vtkSlicerVDModuleLogic vtkSlicerVDModuleLogicPython vtkSlicerVDModuleLogicPythonD qSlicerVDModuleWidgets)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target vtkSlicerVDModuleLogic
add_library(vtkSlicerVDModuleLogic SHARED IMPORTED)

set_target_properties(vtkSlicerVDModuleLogic PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkdouble-conversion;ITKInternalEigen3::Eigen;itksys;TBB::tbb;itkvnl_algo;itkvnl;itkv3p_netlib;itkvcl;ITKCommon;itkNetlibSlatec;ITKStatistics;ITKTransform;ITKMesh;C:/D/S4R/zlib-install/lib/zlib.lib;ITKMetaIO;ITKSpatialObjects;ITKSmoothing;AdaptiveDenoising;ITKIOImageBase;IOScanco;ITKPath;ITKLabelMap;ITKMathematicalMorphology;ITKQuadEdgeMesh;ITKFastMarching;ITKImageFeature;ITKOptimizers;ITKPolynomials;ITKBiasCorrection;ITKColormap;ITKFFT;ITKConvolution;ofstd;oflog;dcmdata;i2d;dcmimgle;dcmimage;dcmjpeg;ijg8;ijg12;ijg16;dcmjpls;dcmtkcharls;dcmtls;dcmnet;dcmsr;cmr;dcmdsig;dcmwlm;dcmqrdb;dcmpstat;dcmrt;dcmiod;dcmfg;dcmseg;dcmtract;dcmpmap;dcmect;ITKDICOMParser;ITKDeformableMesh;ITKDenoising;ITKDeprecated;ITKDiffusionTensorImage;ITKEXPAT;gdcmDICT;gdcmMSFF;ITKznz;ITKniftiio;ITKgiftiio;ITKPDEDeformableRegistration;hdf5_cpp-shared;hdf5-shared;ITKIOBMP;ITKIOBioRad;ITKIOBruker;ITKIOCSV;ITKIODCMTK;ITKIOGDCM;ITKIOIPL;ITKIOGE;ITKIOGIPL;ITKIOHDF5;itkjpeg;ITKIOJPEG;itkopenjpeg;ITKIOJPEG2000;itktiff;ITKIOTIFF;ITKIOLSM;itkminc2;ITKIOMINC;ITKIOMRC;ITKIOMeshBase;ITKIOMeshBYU;ITKIOMeshFreeSurfer;ITKIOMeshGifti;ITKIOMeshOBJ;ITKIOMeshOFF;ITKIOMeshVTK;ITKIOMeta;ITKIONIFTI;ITKNrrdIO;ITKIONRRD;itkpng;ITKIOPNG;ITKIOSiemens;ITKIOXML;ITKIOSpatialObjects;ITKIOStimulate;ITKTransformFactory;ITKIOTransformBase;ITKIOTransformHDF5;ITKIOTransformInsightLegacy;ITKIOTransformMatlab;ITKIOVTK;ITKKLMRegionGrowing;itklbfgs;ITKMarkovRandomFieldsClassifiers;ITKOptimizersv4;ITKQuadEdgeMeshFiltering;ITKRegionGrowing;ITKRegistrationMethodsv4;ITKVTK;ITKWatersheds;ITKReview;ITKTestKernel;ITKVideoCore;ITKVideoIO;ITKVtkGlue;MGHIO;SimpleITKFilters;ITKFactoryRegistration;qSlicerBaseQTCLI;SlicerBaseLogic;MRMLDisplayableManager"
)

# Create imported target vtkSlicerVDModuleLogicPython
add_library(vtkSlicerVDModuleLogicPython MODULE IMPORTED)

set_target_properties(vtkSlicerVDModuleLogicPython PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkSlicerVDModuleLogicPythonD"
)

# Create imported target vtkSlicerVDModuleLogicPythonD
add_library(vtkSlicerVDModuleLogicPythonD SHARED IMPORTED)

set_target_properties(vtkSlicerVDModuleLogicPythonD PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkSlicerVDModuleLogic;vtkWrappingPythonCore;C:/D/S4R/python-install/libs/python36.lib;vtkFiltersFlowPathsPythonD;vtkIOExportPythonD;vtkRenderingGL2PSOpenGL2PythonD;vtkFiltersHybridPythonD;vtkImagingHybridPythonD;vtkRenderingQtPythonD;vtkTestingRenderingPythonD;vtkInfovisCorePythonD;vtkViewsInfovisPythonD;vtkChartsCorePythonD;vtkInfovisLayoutPythonD;vtkPythonInterpreterPythonD;vtkCommonKitPythonD;vtkFiltersKitPythonD;vtkImagingKitPythonD;vtkRenderingKitPythonD;vtkIOKitPythonD;vtkOpenGLKitPythonD;vtkInteractionKitPythonD;vtkViewsKitPythonD;vtkParallelKitPythonD;vtkWrappingKitPythonD;vtkSegmentationCorePythonD;vtkTeemPythonD;vtkITKPythonD;MRMLCorePythonD;MRMLLogicPythonD;vtkAddonPythonD;MRMLDisplayableManagerPythonD;MRMLCLIPythonD;SlicerBaseLogicPythonD;qSlicerBaseQTCLIPythonD;SlicerBaseLogicPythonD;MRMLDisplayableManagerPythonD"
)

# Create imported target qSlicerVDModuleWidgets
add_library(qSlicerVDModuleWidgets SHARED IMPORTED)

set_target_properties(qSlicerVDModuleWidgets PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkSlicerVDModuleLogic;qSlicerBaseQTApp"
)

# Import target "vtkSlicerVDModuleLogic" for configuration "Debug"
set_property(TARGET vtkSlicerVDModuleLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkSlicerVDModuleLogic PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Debug/vtkSlicerVDModuleLogic.lib"
  IMPORTED_LOCATION_DEBUG "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Debug/vtkSlicerVDModuleLogic.dll"
  )

# Import target "vtkSlicerVDModuleLogicPython" for configuration "Debug"
set_property(TARGET vtkSlicerVDModuleLogicPython APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkSlicerVDModuleLogicPython PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Debug/vtkSlicerVDModuleLogicPython.pyd"
  )

# Import target "vtkSlicerVDModuleLogicPythonD" for configuration "Debug"
set_property(TARGET vtkSlicerVDModuleLogicPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkSlicerVDModuleLogicPythonD PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Debug/vtkSlicerVDModuleLogicPythonD.lib"
  IMPORTED_LOCATION_DEBUG "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Debug/vtkSlicerVDModuleLogicPythonD.dll"
  )

# Import target "qSlicerVDModuleWidgets" for configuration "Debug"
set_property(TARGET qSlicerVDModuleWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(qSlicerVDModuleWidgets PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Debug/qSlicerVDModuleWidgets.lib"
  IMPORTED_LOCATION_DEBUG "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Debug/qSlicerVDModuleWidgets.dll"
  )

# Import target "vtkSlicerVDModuleLogic" for configuration "Release"
set_property(TARGET vtkSlicerVDModuleLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkSlicerVDModuleLogic PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Release/vtkSlicerVDModuleLogic.lib"
  IMPORTED_LOCATION_RELEASE "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Release/vtkSlicerVDModuleLogic.dll"
  )

# Import target "vtkSlicerVDModuleLogicPython" for configuration "Release"
set_property(TARGET vtkSlicerVDModuleLogicPython APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkSlicerVDModuleLogicPython PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_LOCATION_RELEASE "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Release/vtkSlicerVDModuleLogicPython.pyd"
  )

# Import target "vtkSlicerVDModuleLogicPythonD" for configuration "Release"
set_property(TARGET vtkSlicerVDModuleLogicPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkSlicerVDModuleLogicPythonD PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Release/vtkSlicerVDModuleLogicPythonD.lib"
  IMPORTED_LOCATION_RELEASE "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Release/vtkSlicerVDModuleLogicPythonD.dll"
  )

# Import target "qSlicerVDModuleWidgets" for configuration "Release"
set_property(TARGET qSlicerVDModuleWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(qSlicerVDModuleWidgets PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Release/qSlicerVDModuleWidgets.lib"
  IMPORTED_LOCATION_RELEASE "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/Release/qSlicerVDModuleWidgets.dll"
  )

# Import target "vtkSlicerVDModuleLogic" for configuration "MinSizeRel"
set_property(TARGET vtkSlicerVDModuleLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkSlicerVDModuleLogic PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/vtkSlicerVDModuleLogic.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/vtkSlicerVDModuleLogic.dll"
  )

# Import target "vtkSlicerVDModuleLogicPython" for configuration "MinSizeRel"
set_property(TARGET vtkSlicerVDModuleLogicPython APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkSlicerVDModuleLogicPython PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_MINSIZEREL ""
  IMPORTED_LOCATION_MINSIZEREL "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/vtkSlicerVDModuleLogicPython.pyd"
  )

# Import target "vtkSlicerVDModuleLogicPythonD" for configuration "MinSizeRel"
set_property(TARGET vtkSlicerVDModuleLogicPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkSlicerVDModuleLogicPythonD PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/vtkSlicerVDModuleLogicPythonD.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/vtkSlicerVDModuleLogicPythonD.dll"
  )

# Import target "qSlicerVDModuleWidgets" for configuration "MinSizeRel"
set_property(TARGET qSlicerVDModuleWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(qSlicerVDModuleWidgets PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/qSlicerVDModuleWidgets.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/qSlicerVDModuleWidgets.dll"
  )

# Import target "vtkSlicerVDModuleLogic" for configuration "RelWithDebInfo"
set_property(TARGET vtkSlicerVDModuleLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkSlicerVDModuleLogic PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/vtkSlicerVDModuleLogic.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/vtkSlicerVDModuleLogic.dll"
  )

# Import target "vtkSlicerVDModuleLogicPython" for configuration "RelWithDebInfo"
set_property(TARGET vtkSlicerVDModuleLogicPython APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkSlicerVDModuleLogicPython PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELWITHDEBINFO ""
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/vtkSlicerVDModuleLogicPython.pyd"
  )

# Import target "vtkSlicerVDModuleLogicPythonD" for configuration "RelWithDebInfo"
set_property(TARGET vtkSlicerVDModuleLogicPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkSlicerVDModuleLogicPythonD PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/vtkSlicerVDModuleLogicPythonD.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/vtkSlicerVDModuleLogicPythonD.dll"
  )

# Import target "qSlicerVDModuleWidgets" for configuration "RelWithDebInfo"
set_property(TARGET qSlicerVDModuleWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(qSlicerVDModuleWidgets PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/qSlicerVDModuleWidgets.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/dev/SlicerFirstExtension/VirtualDissection-build/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/qSlicerVDModuleWidgets.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
